services:
  portfolio:
    container_name: "definitely_not_the_development_container"
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - path: ./.env
        required: true