git pull
docker compose up --build --remove-orphans -d
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
echo "CS 546 is awesome!"
