git pull
docker compose up --build --remove-orphans -d
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
echo "Hello world!"
